//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.Timetable.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.Timetable.Resources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string EventEnd {
            get {
                return ResourceManager.GetString("EventEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom (Days).
        /// </summary>
        internal static string EventRepeatCustomDays {
            get {
                return ResourceManager.GetString("EventRepeatCustomDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Until.
        /// </summary>
        internal static string EventRepeatUntil {
            get {
                return ResourceManager.GetString("EventRepeatUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string EventStart {
            get {
                return ResourceManager.GetString("EventStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string EventTitle {
            get {
                return ResourceManager.GetString("EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event is part of a group. Do you want to move all related events in the same manner?.
        /// </summary>
        internal static string GroupMoveDescription {
            get {
                return ResourceManager.GetString("GroupMoveDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import type.
        /// </summary>
        internal static string ImportType {
            get {
                return ResourceManager.GetString("ImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Events.
        /// </summary>
        internal static string MoveGroup {
            get {
                return ResourceManager.GetString("MoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only This.
        /// </summary>
        internal static string MoveSingle {
            get {
                return ResourceManager.GetString("MoveSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition.
        /// </summary>
        internal static string RepetitionType {
            get {
                return ResourceManager.GetString("RepetitionType", resourceCulture);
            }
        }
    }
}
